language: ruby

rvm:
  - 1.9.3
  - 2.0.0

env:
  - RAILS_VERSION=3.1.4
  - RAILS_VERSION=3.2.9
  - RAILS_VERSION=3-1-stable
  - RAILS_VERSION=3-2-stable

before_script:
  - mysql -e 'create database dev_test;'
  - bundle exec rake db:migrate

branches:
  only:
    - master
