language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head

env:
  - RAILS_VERSION=3.1.4
  - RAILS_VERSION=3.2.2
  - RAILS_VERSION=3-1-stable
  - RAILS_VERSION=3-2-stable
  # - RAILS_VERSION=master

matrix:
  exclude:
    - rvm: 1.9.2
      env: RAILS_VERSION=master

before_script:
  - mysql -e 'create database foxweb_dev_test;'