language: ruby

rvm:
  - 1.9.2
  - 1.9.3

env:
  - RAILS_VERSION=3.1.4
  - RAILS_VERSION=3.2.6
  - RAILS_VERSION=3-1-stable
  - RAILS_VERSION=3-2-stable

before_script:
  - mysql -e 'create database foxweb_dev_test;'
  - bundle exec rake db:migrate
