development:
  adapter: mysql2
  database: foxweb_dev_dev
  encoding: utf8
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: dev_test
  encoding: utf8
  username: root

production:
  adapter: mysql2
  database: foxweb_dev_dev
  encoding: utf8
  username: root
  password:
  host: localhost
